CREATE TABLE artist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    followers INTEGER NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE album (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    artist_id INTEGER NOT NULL,
    tracks INTEGER NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES artist(id)
);